name: Angular Frontend

on:
  push:
    branches: [ main, develop ]
    paths:
      - "frontend-vibe/**"
      - ".github/workflows/angular-test-frontend.yml"
  pull_request:
    branches: [ main, develop ]
    paths:
      - "frontend-vibe/**"
      - ".github/workflows/angular-test-frontend.yml"

env:
  PROJECT_DIRECTORY: 'frontend-vibe'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16.x ]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./${{ env.PROJECT_DIRECTORY }}
          push: false
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/vibe-angular-frontend:latest
