name: .NET OpenFace Api Test

on:
  push:
    branches: [ main, develop ]
    paths:
      - "VIBEBackend/OpenFaceService/**"
      - ".github/workflows/dotnet-test-openface-api.yml"
  pull_request:
    branches: [ main, develop ]
    paths:
      - "VIBEBackend/OpenFaceService/**"
      - ".github/workflows/dotnet-test-openface-api.yml"

env:
  PROJECT_PATH: 'VIBEBackend/OpenFaceService/OpenFaceService.csproj'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: 'Restore packages'
        run: dotnet restore ${{ env.PROJECT_PATH }}
      - name: 'Build project'
        run: dotnet build ${{ env.PROJECT_PATH }} --no-restore --configuration Release
